Add tests & simplify logic
6529-Collections/nftdelegation pull request #3
Opened 2022-12-23 21:29 UTC by scooprinder

I agree with the comments made in [1](https://github.com/6529-Collections/nftdelegation/pull/1) and as such haven't made any modifications to errors or syntax. 

Simplified the logic for the register / revoke functions, though upon further reflection these could be improved further (perhaps with different storage layouts). Knocked off around 45k gas from `register` and around 10k gas from `revoke`. 

I added some simple forge tests to cover the base use cases and found the following issues:

* The `require(registeredDelegation[globalHash] == false);` check in `registerDelegationAddress` means that it is impossible to add more than one `delegationAddresses` per hash (which makes the most of the mapping redundant). 
* Both `retrieveActiveFromDelegations` and `retrieveActiveToDelegations` create fixed size arrays matching all delegations. This means that it could return an array with address(0) elements. For example, if the `delegationAddresses[]` for a given hash has 3 entries, two of which are expired in slots 0 and 1 then with the current implementation would return `[0x000..., 0x000..., <delegation address>]` - for large array sizes this would require further processing to get the correct information. 
* Counter mappings weren't strictly necessary, could just use the `length` of the returning `delegationAddresses[]` for a given hash.

The code in this PR isn't perfect either but I think some more fundamental changes are required - I'm submitting it because it could be some help but no drama if it isn't.

2022-12-25 00:05 UTC, rookmate commented on test/DelegationManagement.t.sol
> +    function testRetieveActiveTo() public {
Fix typo: `testRetieveActiveTo` to `testRetrieveActiveTo`

2022-12-25 12:02 UTC, rookmate requested changes
I've tested it on my end, but can't commit the changes so I'll leave the review here

2022-12-25 12:02 UTC, rookmate commented on test/DelegationManagement.t.sol
> +
Add below:
```    address public collection;
    address public collection2;
    address public delegationAddr;
    address public delegationAddr2;
    uint256 usecase;
    uint256 ts;

2022-12-25 12:02 UTC, rookmate commented on test/DelegationManagement.t.sol
> +        delegation = new delegationManagement();
add below:
```
        collection = vm.addr(1);
        collection2 = vm.addr(2);
        delegationAddr = vm.addr(11);
        delegationAddr2 = vm.addr(12);
        usecase = bound(usecase, 1, 14);
        ts = 1;

2022-12-25 12:02 UTC, rookmate commented on test/DelegationManagement.t.sol
> +
Remove the inputs above as they can be fuzzed on setup

2022-12-25 12:02 UTC, rookmate commented on test/DelegationManagement.t.sol
> +
Remove the inputs above as they can be fuzzed on setup

2022-12-25 12:02 UTC, rookmate commented on test/DelegationManagement.t.sol
> +
Remove the inputs above as they can be fuzzed on setup

2022-12-25 12:02 UTC, rookmate commented on test/DelegationManagement.t.sol
> +
Remove the inputs above as they can be fuzzed on setup

2022-12-25 12:02 UTC, rookmate commented on test/DelegationManagement.t.sol
> +
Remove the inputs above as they can be fuzzed on setup

2022-12-25 12:02 UTC, rookmate commented on test/DelegationManagement.t.sol
> +
Remove the inputs above as they can be fuzzed on setup

2023-01-09 03:38 UTC, scooprinder commented
Apologies for the delay @rookmate - I appreciate your feedback; are these tests still wanted? I can tidy the PR up this week if so.

2023-01-09 19:02 UTC, rookmate commented
> Apologies for the delay @rookmate - I appreciate your feedback; are these tests still wanted? I can tidy the PR up this week if so.

Hey mate! Me and @brookr from PR #19 really want it! :pray: Although we're waiting for the repo owner to come alive and also provide feedback in the PRs...

I just noticed they did more than a few changes a few days ago :thinking: If I get some time this week I'll do another pass on the open PRs

2023-04-11 11:03 UTC, a2rocket commented
outdated PR

2023-04-11 11:03 UTC, closed without merging