Added hardhat and unit tests
6529-Collections/nftdelegation pull request #31
Opened 2023-02-03 00:47 UTC by omnus

* Installed hardhat
* Moved contract into 'contracts' folder
* Added example unit tests

2023-02-05 07:58 UTC, brookr requested changes
Thanks for this! Would love to see this project integrate some tests! I don't think this is quite ready for direct merge, very minor notes in the review.

2023-02-05 07:58 UTC, brookr commented on package.json
> +    "url": "git+https://github.com/omnus/nftdelegation.git"
If this is to be merged, it should match the target repo?

2023-02-05 07:58 UTC, brookr commented on test/DelegationManagement.js
> +
```suggestion
```

2023-02-05 07:58 UTC, brookr commented on package.json
> +    "url": "https://github.com/omnus/nftdelegation/issues"
same

2023-02-05 07:58 UTC, brookr commented on package.json
> +  "homepage": "https://github.com/omnus/nftdelegation#readme",
same

2023-02-05 07:58 UTC, brookr commented on package.json
> +  "version": "1.0.0",
Would love to see SEMVER, but this project doesn't seem to be using it... yet?

2023-02-05 07:58 UTC, brookr commented on .gitignore
> +artifacts
```suggestion
artifacts

```

2023-02-05 07:58 UTC, brookr commented on .gitignore
> +artifacts
...just to get rid of the "no newline at end of file" indicator in the PR :P

2023-04-11 11:03 UTC, a2rocket commented
outdated PR

2023-04-11 11:03 UTC, closed without merging